_core:
  default_config_hash: sA5ddc-TaNzoXWVoUeF1VA7vc7EsMA-x7Q4rtwHztuw
vfd_table:
  -
    view: favorites
    field: field_audio
    field_type: media
    remove: Remove
  -
    view: favorites
    field: field_img
    field_type: media
    remove: Remove
  -
    view: favorites
    field: field_video
    field_type: media
    remove: Remove
